/* This file was autogenerated. Do not edit! */
#ifndef _INCL_MOJOSHADER_VERSION_H_
#define _INCL_MOJOSHADER_VERSION_H_
#define MOJOSHADER_VERSION 1132
#define MOJOSHADER_CHANGESET "hg-1132:b784577caefa"
#endif

